/**
 * TACET domain — foundational types.
 *
 * Pure domain. No I/O, no framework, no model calls. These names mirror the
 * production (Java) version so this prototype is its executable spec.
 *
 * A note on philosophy that constrains every type here: a reader certifies
 * COHERENCE, never TRUTH. Nothing in this module models "is this claim true".
 * It models how well the evidence supports a claim, and the structure of how
 * two undecided readers relate to it.
 */

/** A pointer to where a piece of evidence came from. We keep "how to reach the
 * source", not the raw third-party content. */
export interface Provenance {
  readonly sourceId: string;
  /** Human-citable reference (e.g. DOI, URL, archive locator). */
  readonly locator: string;
  /** ISO date of the source, when known. Time is METADATA, never a decision
   * rule — it informs the reliability profile and the final temporal layer,
   * it does not make a reader conclude "newer wins". */
  readonly date?: string;
  /** Coarse classification used by the coverage audit (language family,
   * geographic locus, stakeholder class, source genre). */
  readonly tags?: Readonly<Record<string, string>>;
  /** Whether the language-family tag came from a DECLARED language code or was
   * DEFAULTED (provisional) because the source declared none ("und"/absent). As
   * honest as `summaryMethod` is about the summary: the data states what was
   * assumed vs. declared. Real language inference (and the "unknown" family for
   * undetectable cases) arrives after the LLM phase. */
  readonly languageSource?: "declared" | "defaulted";
  /** Authors of the source, "Given Family" display form, when known. */
  readonly authors?: readonly string[];
  /** Container/venue (journal, book) of the source, when known. */
  readonly venue?: string;
  /** Human-readable summary of the source. When `summaryMethod` is
   * "truncated-stub" this is the first ~1000 chars of the cleaned abstract; when
   * "llm" it is the `structured.summaryText`. */
  readonly summary?: string;
  /** How `summary` was produced. "truncated-stub" = deterministic placeholder
   * (offline, honest, like the StubReader); "llm" = generated by the summarizer
   * (`npm run summarize`, run once in prep with a key). The two COEXIST: anyone
   * without a key keeps truncated-stub. */
  readonly summaryMethod?: "truncated-stub" | "llm";
  /** Structured LLM summary, present only when `summaryMethod` is "llm". The
   * structured fields are produced for the LlmReader (Phase 5b); the demo uses
   * `summary` (= `structured.summaryText`). */
  readonly structured?: StructuredSummary;
  /** For a source read locally but NOT redistributed (e.g. an arXiv PDF): which
   * file, by sha256, and a short locus. Provenance without the bytes — survives
   * redaction so the public fixture can name + verify the source. */
  readonly sourceAnchor?: SourceAnchor;
}

/** A pointer to a locally-read, non-redistributed source: the file, its sha256
 * (verification), and a short human locus. The bytes are never published. */
export interface SourceAnchor {
  readonly file: string;
  readonly sha256: string;
  readonly locus?: string;
}

/** Where a paper stands on the SARS-CoV-2 origin question. "none" when the paper
 * takes no origin position (most of the corpus is about other aspects — that is
 * correct and common). */
export type OriginStance = "zoonotic" | "lab" | "both-considered" | "none";

/** A structured summary grounded ONLY in the source abstract (no external
 * knowledge). Produced by the LLM summarizer; consumed by the LlmReader. */
export interface StructuredSummary {
  /** The paper's central claim, one sentence. */
  readonly centralClaim: string;
  /** The evidence the paper invokes, 1-2 sentences. */
  readonly citedEvidence: string;
  /** The paper's stance on SARS-CoV-2 origin. */
  readonly originStance: OriginStance;
  /** 2-3 sentences of prose for human reading. */
  readonly summaryText: string;
}

/** An atomic assertion extracted from the evidence base, with its provenance. */
export interface Claim {
  readonly id: string;
  readonly text: string;
  readonly provenance: readonly Provenance[];
  /** Whether this claim's SOURCE may be redistributed. Absent/true = open (the
   * CC-BY corpus). false = TACET read the source locally (e.g. an arXiv PDF) but
   * the public fixture must carry only the JUDGMENT + provenance (DOI + sha256 +
   * lean), never the text or summary — redacted at freeze. TACET reviews evidence,
   * it does not redistribute it. */
  readonly redistributable?: boolean;
}

/** A reader's stance on a single claim, produced from the evidence and held
 * undecided at the outset. NOT a verdict on truth. */
export type Lean = "supports" | "contradicts" | "insufficient";

export interface ReaderJudgement {
  /** Which reader SLOT produced this — "reader-a" / "reader-b". The convergence
   * map keys leans by this. A judgement without an author is incomplete. */
  readonly readerId: string;
  /** The MODEL that actually produced this lean (e.g. "glm-4.6",
   * "minimax/minimax-m2.7", "google/gemma-4-31b-it:free", or "stub"). Mandatory:
   * with a fallback reader the pair composition can vary per claim (one claim
   * GLM-vs-M2.7, another GLM-vs-Gemma), so every disagreement must be auditable
   * back to who produced each lean. */
  readonly readerModel: string;
  readonly claimId: string;
  readonly lean: Lean;
  /** Sources the reader could actually cite back to for this lean. If empty,
   * the claim is unsupported by the evidence the reader read. */
  readonly citedSources: readonly string[];
  /** Free-text rationale, grounded in cited sources. */
  readonly rationale: string;
}
